schema-version: v2
kind: plugin
metadata:
  name: go-template-base
  display-name: go-template-base
  description: golang template base
  version: 2.0.9
  picture: plugin.png

spec:
  type: app
  compatibility:
    - golang
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: https://github.com/cassiolpaixao90/labs-stk-go/tree/main
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  stk-projects-only: false
  inputs:
    - label: Nome do projeto
      name: project_name
      type: text
      required: true
      help: 'Inform your project name'
      global: true

    - label: Golang Version
      name: version_golang
      type: select
      items:
        - '1.21'
        - '1.20'
        - '1.19'
        - '1.18'

    - label: Nome do recurso
      name: resource
      type: text
      required: true
      help: 'Inform your resource name'
      global: true

    - label: Porta da aplicacao
      name: port
      type: text
      required: true
      help: 'Inform your port'
      global: true

  computed-inputs:
    custom_resource: "{{resource|capitalize}}"

  hooks:
    - type: run
      trigger: after-render
      commands:
        - go mod tidy
        - echo project generated
      working-dir: "app"