schema-version: v2
kind: plugin
metadata:
  name: go-template-base
  display-name: go-template-base
  description: golang template base
  version: 0.0.1
  picture: plugin.png
  target_path: Path

spec:
  type: python
  compatibility:
    - golang
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: https://github.com/cassiolpaixao90/labs-stk-go/tree/main
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  stk-projects-only: false
  inputs:
    - label: Nome do projeto
      name: nome_projeto
      type: text
      required: true
      pattern: '([a-z]+)+'
      help: 'Inform your project name'
    - label: Golang Version
      name: version_golang
      type: select
      items:
        - '1.20'
        - '1.19'
        - '1.18'
  hooks:
    - type: run
      trigger: after-render
      working-dir: "{{target_path}}/app"
      linux:
        - go mod tidy
      windows:
        - go mod tidy
      mac:
        - go mod tidy
